"""Generate the test-only fi font header; requires fonttools==4.61.1.

All outlines are simple rectangles authored for this test, under the repository's
MIT license. No installed or third-party font is read or redistributed.
Run from any directory; output is tests/ligature_fixture.hpp.
"""
from pathlib import Path
from io import BytesIO
import hashlib

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.feaLib.builder import addOpenTypeFeaturesFromString

builder = FontBuilder(1000, isTTF=True)
glyph_order = [".notdef", "f", "i", "x", "fi"]
widths = [400, 500, 250, 500, 650]
builder.setupGlyphOrder(glyph_order)
builder.setupCharacterMap({0x66: "f", 0x69: "i", 0x78: "x"})
glyphs = {}
for name, width in zip(glyph_order, widths):
    pen = TTGlyphPen(None)
    if name != ".notdef":
        pen.moveTo((50, 0))
        pen.lineTo((width - 50, 0))
        pen.lineTo((width - 50, 700))
        pen.lineTo((50, 700))
        pen.closePath()
    glyphs[name] = pen.glyph()
builder.setupGlyf(glyphs)
builder.setupHorizontalMetrics({name: (width, 0)
                                for name, width in zip(glyph_order, widths)})
builder.setupHorizontalHeader(ascent=800, descent=-200)
builder.setupNameTable({
    "familyName": "LumaText Test Ligature",
    "styleName": "Regular",
    "uniqueFontIdentifier": "LumaTextTestLigature1",
    "fullName": "LumaText Test Ligature",
    "psName": "LumaTextTestLigature",
    "version": "Version 1.000",
})
builder.setupOS2(sTypoAscender=800, sTypoDescender=-200,
                 usWinAscent=800, usWinDescent=200)
builder.setupPost()
builder.setupMaxp()
# Fixed SFNT timestamps make regeneration byte-for-byte reproducible.
builder.font["head"].created = builder.font["head"].modified = 2082844800
builder.font.recalcTimestamp = False
addOpenTypeFeaturesFromString(builder.font, """
    languagesystem DFLT dflt;
    languagesystem latn dflt;
    feature liga { sub f i by fi; } liga;
""")
output = BytesIO()
builder.save(output)
data = output.getvalue()
rows = ["  " + ", ".join(f"0x{value:02x}" for value in data[index:index + 16]) + ","
        for index in range(0, len(data), 16)]
header = (
    "#pragma once\n\n"
    "// Generated by tools/generate_ligature_test_font.py. Test-only MIT-licensed\n"
    "// rectangle outlines with explicit fi substitution; no third-party font.\n"
    f"// SHA-256: {hashlib.sha256(data).hexdigest()}\n"
    "namespace lt_test {\ninline constexpr unsigned char ligature_font[] = {\n" +
    "\n".join(rows) + "\n};\n}  // namespace lt_test\n"
)
path = Path(__file__).resolve().parents[1] / "tests" / "ligature_fixture.hpp"
path.write_text(header, encoding="utf-8")
print(f"Wrote {len(data)} font bytes to {path}")
