#!/usr/bin/env python3
"""Generate the compact Unicode properties used by LumaText grapheme breaking."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import urllib.request


UNICODE_VERSION = "16.0.0"
FILES = {
    "GraphemeBreakProperty.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/auxiliary/"
        "GraphemeBreakProperty.txt",
        "c29360bd6f7132811d701d29069541e827eb44bfc4c8fbde8c370d6982689dc1",
    ),
    "emoji-data.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/emoji/emoji-data.txt",
        "f1365a5173eee18e1f98b240cdc492e84a25f1ce7e0c9d1094eb29c41a22696a",
    ),
    "DerivedCoreProperties.txt": (
        f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/"
        "DerivedCoreProperties.txt",
        "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd",
    ),
}

GRAPHEME_VALUES = {
    "CR": 1,
    "LF": 2,
    "Control": 3,
    "Extend": 4,
    "ZWJ": 5,
    "Regional_Indicator": 6,
    "Prepend": 7,
    "SpacingMark": 8,
    "L": 9,
    "V": 10,
    "T": 11,
    "LV": 12,
    "LVT": 13,
}
INDIC_VALUES = {"Consonant": 1, "Linker": 2, "Extend": 3}


def ensure_file(directory: pathlib.Path, name: str) -> pathlib.Path:
    url, expected_hash = FILES[name]
    path = directory / name
    if not path.exists():
        directory.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(url, path)
    actual_hash = hashlib.sha256(path.read_bytes()).hexdigest()
    if actual_hash != expected_hash:
        raise RuntimeError(f"SHA-256 mismatch for {name}: {actual_hash}")
    return path


def records(path: pathlib.Path):
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        bounds = fields[0].split("..")
        first = int(bounds[0], 16)
        last = int(bounds[-1], 16)
        yield first, last, fields[1:]


def set_range(values: bytearray, first: int, last: int, mask: int, value: int):
    for codepoint in range(first, last + 1):
        values[codepoint] = (values[codepoint] & ~mask) | value


def generate(directory: pathlib.Path, output: pathlib.Path):
    grapheme_path = ensure_file(directory, "GraphemeBreakProperty.txt")
    emoji_path = ensure_file(directory, "emoji-data.txt")
    derived_path = ensure_file(directory, "DerivedCoreProperties.txt")

    values = bytearray(0x110000)
    for first, last, fields in records(grapheme_path):
        property_name = fields[0]
        if property_name in GRAPHEME_VALUES:
            set_range(values, first, last, 0x0F, GRAPHEME_VALUES[property_name])
    for first, last, fields in records(derived_path):
        if len(fields) >= 2 and fields[0] == "InCB" and fields[1] in INDIC_VALUES:
            set_range(values, first, last, 0x30, INDIC_VALUES[fields[1]] << 4)
    for first, last, fields in records(emoji_path):
        if fields[0] == "Extended_Pictographic":
            set_range(values, first, last, 0x40, 0x40)

    ranges = []
    first = 0
    while first < len(values):
        value = values[first]
        last = first
        while last + 1 < len(values) and values[last + 1] == value:
            last += 1
        if value:
            ranges.append((first, last, value))
        first = last + 1

    lines = [
        "// Generated by tools/generate_unicode_grapheme_data.py.",
        f"// Unicode {UNICODE_VERSION}; do not edit manually.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace lt::unicode::data {",
        "",
        "struct PropertyRange {",
        "  char32_t first;",
        "  char32_t last;",
        "  uint8_t value;",
        "};",
        "",
        "inline constexpr PropertyRange kPropertyRanges[] = {",
    ]
    lines.extend(
        f"    {{0x{first:04x}, 0x{last:04x}, 0x{value:02x}}},"
        for first, last, value in ranges
    )
    lines.extend(["};", "", "}  // namespace lt::unicode::data", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {len(ranges)} ranges to {output}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--unicode-dir", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    generate(args.unicode_dir, args.output)


if __name__ == "__main__":
    main()
